# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90e79f4a1a1ff0cb42046b510f79466f9b72a08df548e00bea6c775a885acb621c4de662b2547e001e6c5832b6c1d2e26f87285c6034b5cd19946552f82636c0

test:
  secret_key_base: 5fa38a0a10eb88cc6cf02497f5c8132b4e2e002b701486dddeda80a3c99a646878cc038d9bb099dfbb972499d959b5f61e863e14837d5dbe2185a1faf48115e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
